// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'zz.ide.models.Context' );
goog.provide( 'zz.ide.models.ContextDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );



/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
zz.ide.models.ContextDatarow = function( dataset, opt_data ){

    /**
     * @type {boolean}
     */
    this.isContextOpen = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( zz.ide.models.ContextDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
zz.ide.models.Context = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( zz.ide.models.Context, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {zz.ide.models.ContextDatarow}
*/
zz.ide.models.Context.prototype.DatarowConstructor = zz.ide.models.ContextDatarow;

/**
* Return zz.ide.models.ContextDatarow schema object.
* @override
* @returns {Object}
*/
zz.ide.models.Context.prototype.getDatarowSchema = function( ){

return {
        isContextOpen: {
                index: 1,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        }
};
};