// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'zz.ide.models.Error' );
goog.provide( 'zz.ide.models.ErrorDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );



/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
zz.ide.models.ErrorDatarow = function( dataset, opt_data ){

    /**
     * @type {boolean}
     */
    this.showClose = undefined;

    /**
     * @type {boolean}
     */
    this.showResize = undefined;

    /**
     * @type {number}
     */
    this.height = undefined;

    /**
     * @type {number}
     */
    this.width = undefined;

    /**
     * @type {string}
     */
    this.title = undefined;

    /**
     * @type {number}
     */
    this.top = undefined;

    /**
     * @type {number}
     */
    this.left = undefined;

    /**
     * @type {string}
     */
    this.text = undefined;

    /**
     * @type {string}
     */
    this.icon = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( zz.ide.models.ErrorDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
zz.ide.models.Error = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( zz.ide.models.Error, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {zz.ide.models.ErrorDatarow}
*/
zz.ide.models.Error.prototype.DatarowConstructor = zz.ide.models.ErrorDatarow;

/**
* Return zz.ide.models.ErrorDatarow schema object.
* @override
* @returns {Object}
*/
zz.ide.models.Error.prototype.getDatarowSchema = function( ){

return {
        showClose: {
                index: 0,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: true
        },
        showResize: {
                index: 1,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: true
        },
        height: {
                index: 2,
                type: zz.models.enums.FieldType.NUMBER,
                required: true
        },
        width: {
                index: 3,
                type: zz.models.enums.FieldType.NUMBER,
                required: true
        },
        title: {
                index: 4,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        top: {
                index: 5,
                type: zz.models.enums.FieldType.NUMBER,
                required: false
        },
        left: {
                index: 6,
                type: zz.models.enums.FieldType.NUMBER,
                required: false
        },
        text: {
                index: 7,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        icon: {
                index: 8,
                type: zz.models.enums.FieldType.STRING,
                required: false
        }
};
};