// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'zz.ide.models.Layout' );
goog.provide( 'zz.ide.models.LayoutDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );

goog.require( 'zz.ide.models.Header' );
goog.require( 'zz.ide.models.Navigation' );
goog.require( 'zz.ide.models.Ace' );


/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
zz.ide.models.LayoutDatarow = function( dataset, opt_data ){

    /**
     * @type {zz.ide.models.Header}
     */
    this.header = undefined;

    /**
     * @type {zz.ide.models.Navigation}
     */
    this.navigation = undefined;

    /**
     * @type {zz.ide.models.Ace}
     */
    this.ace = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( zz.ide.models.LayoutDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
zz.ide.models.Layout = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( zz.ide.models.Layout, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {zz.ide.models.LayoutDatarow}
*/
zz.ide.models.Layout.prototype.DatarowConstructor = zz.ide.models.LayoutDatarow;

/**
* Return zz.ide.models.LayoutDatarow schema object.
* @override
* @returns {Object}
*/
zz.ide.models.Layout.prototype.getDatarowSchema = function( ){

return {
        header: {
                index: 0,
                type: zz.ide.models.Header,
                required: false
        },
        navigation: {
                index: 1,
                type: zz.ide.models.Navigation,
                required: false
        },
        ace: {
                index: 2,
                type: zz.ide.models.Ace,
                required: false
        }
};
};