// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'zz.ide.models.Layout' );
goog.provide( 'zz.ide.models.LayoutDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );

goog.require( 'zz.ide.models.Header' );
goog.require( 'zz.ide.models.Navigation' );
goog.require( 'zz.ide.models.Modal' );
goog.require( 'zz.ide.models.Error' );
goog.require( 'zz.ide.models.Popup' );


/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
zz.ide.models.LayoutDatarow = function( dataset, opt_data ){

    /**
     * @type {zz.ide.models.Header}
     */
    this.header = undefined;

    /**
     * @type {zz.ide.models.Navigation}
     */
    this.navigation = undefined;

    /**
     * @type {zz.ide.models.Modal}
     */
    this.modal = undefined;

    /**
     * @type {zz.ide.models.Error}
     */
    this.error = undefined;

    /**
     * @type {zz.ide.models.Popup}
     */
    this.popup = undefined;

    /**
     * @type {boolean}
     */
    this.addBtnShow = undefined;

    /**
     * @type {boolean}
     */
    this.navigationIsShown = undefined;

    /**
     * @type {boolean}
     */
    this.headerIsShown = undefined;

    /**
     * @type {boolean}
     */
    this.compiling = undefined;

    /**
     * @type {boolean}
     */
    this.compilingSoy = undefined;

    /**
     * @type {boolean}
     */
    this.compilingStyles = undefined;

    /**
     * @type {boolean}
     */
    this.compilingModels = undefined;

    /**
     * @type {boolean}
     */
    this.calculatingDeps = undefined;

    /**
     * @type {boolean}
     */
    this.extractingMsg = undefined;

    /**
     * @type {boolean}
     */
    this.compileBtnBlur = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( zz.ide.models.LayoutDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
zz.ide.models.Layout = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( zz.ide.models.Layout, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {zz.ide.models.LayoutDatarow}
*/
zz.ide.models.Layout.prototype.DatarowConstructor = zz.ide.models.LayoutDatarow;

/**
* Return zz.ide.models.LayoutDatarow schema object.
* @override
* @returns {Object}
*/
zz.ide.models.Layout.prototype.getDatarowSchema = function( ){

return {
        header: {
                index: 0,
                type: zz.ide.models.Header,
                required: false
        },
        navigation: {
                index: 1,
                type: zz.ide.models.Navigation,
                required: false
        },
        modal: {
                index: 2,
                type: zz.ide.models.Modal,
                required: false
        },
        error: {
                index: 3,
                type: zz.ide.models.Error,
                required: false
        },
        popup: {
                index: 4,
                type: zz.ide.models.Popup,
                required: false
        },
        addBtnShow: {
                index: 5,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        },
        navigationIsShown: {
                index: 6,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        },
        headerIsShown: {
                index: 7,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        },
        compiling: {
                index: 8,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        },
        compilingSoy: {
                index: 9,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        },
        compilingStyles: {
                index: 10,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        },
        compilingModels: {
                index: 11,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        },
        calculatingDeps: {
                index: 12,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        },
        extractingMsg: {
                index: 13,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        },
        compileBtnBlur: {
                index: 14,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        }
};
};