// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'zz.ide.models.Modal' );
goog.provide( 'zz.ide.models.ModalDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );



/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
zz.ide.models.ModalDatarow = function( dataset, opt_data ){

    /**
     * @type {string}
     */
    this.id = undefined;

    /**
     * @type {string}
     */
    this.title = undefined;

    /**
     * @type {boolean}
     */
    this.showClose = undefined;

    /**
     * @type {boolean}
     */
    this.showResize = undefined;

    /**
     * @type {number}
     */
    this.height = undefined;

    /**
     * @type {number}
     */
    this.width = undefined;

    /**
     * @type {number}
     */
    this.top = undefined;

    /**
     * @type {number}
     */
    this.left = undefined;

    /**
     * @type {string}
     */
    this.icon = undefined;

    /**
     * @type {string}
     */
    this.className = undefined;

    /**
     * @type {boolean}
     */
    this.show = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( zz.ide.models.ModalDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
zz.ide.models.Modal = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( zz.ide.models.Modal, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {zz.ide.models.ModalDatarow}
*/
zz.ide.models.Modal.prototype.DatarowConstructor = zz.ide.models.ModalDatarow;

/**
* Return zz.ide.models.ModalDatarow schema object.
* @override
* @returns {Object}
*/
zz.ide.models.Modal.prototype.getDatarowSchema = function( ){

return {
        id: {
                index: 0,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        title: {
                index: 1,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        showClose: {
                index: 2,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: true
        },
        showResize: {
                index: 3,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: true
        },
        height: {
                index: 4,
                type: zz.models.enums.FieldType.NUMBER,
                required: false
        },
        width: {
                index: 5,
                type: zz.models.enums.FieldType.NUMBER,
                required: false
        },
        top: {
                index: 6,
                type: zz.models.enums.FieldType.NUMBER,
                required: false
        },
        left: {
                index: 7,
                type: zz.models.enums.FieldType.NUMBER,
                required: false
        },
        icon: {
                index: 8,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        className: {
                index: 9,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        show: {
                index: 10,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        }
};
};