// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'zz.ide.models.ModalAddFile' );
goog.provide( 'zz.ide.models.ModalAddFileDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );



/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
zz.ide.models.ModalAddFileDatarow = function( dataset, opt_data ){

    /**
     * @type {string}
     */
    this.name = undefined;

    /**
     * @type {number}
     */
    this.type = undefined;

    /**
     * @type {string}
     */
    this.path = undefined;

    /**
     * @type {string}
     */
    this.error = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( zz.ide.models.ModalAddFileDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
zz.ide.models.ModalAddFile = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( zz.ide.models.ModalAddFile, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {zz.ide.models.ModalAddFileDatarow}
*/
zz.ide.models.ModalAddFile.prototype.DatarowConstructor = zz.ide.models.ModalAddFileDatarow;

/**
* Return zz.ide.models.ModalAddFileDatarow schema object.
* @override
* @returns {Object}
*/
zz.ide.models.ModalAddFile.prototype.getDatarowSchema = function( ){

return {
        name: {
                index: 0,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        type: {
                index: 1,
                type: zz.models.enums.FieldType.NUMBER,
                required: false
        },
        path: {
                index: 2,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        error: {
                index: 3,
                type: zz.models.enums.FieldType.STRING,
                required: false
        }
};
};