// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'zz.ide.models.ModalRenameFile' );
goog.provide( 'zz.ide.models.ModalRenameFileDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );



/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
zz.ide.models.ModalRenameFileDatarow = function( dataset, opt_data ){

    /**
     * @type {string}
     */
    this.path = undefined;

    /**
     * @type {string}
     */
    this.path2 = undefined;

    /**
     * @type {string}
     */
    this.error = undefined;

    /**
     * @type {string}
     */
    this.name = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( zz.ide.models.ModalRenameFileDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
zz.ide.models.ModalRenameFile = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( zz.ide.models.ModalRenameFile, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {zz.ide.models.ModalRenameFileDatarow}
*/
zz.ide.models.ModalRenameFile.prototype.DatarowConstructor = zz.ide.models.ModalRenameFileDatarow;

/**
* Return zz.ide.models.ModalRenameFileDatarow schema object.
* @override
* @returns {Object}
*/
zz.ide.models.ModalRenameFile.prototype.getDatarowSchema = function( ){

return {
        path: {
                index: 0,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        path2: {
                index: 1,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        error: {
                index: 2,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        name: {
                index: 3,
                type: zz.models.enums.FieldType.STRING,
                required: false
        }
};
};