// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'zz.ide.models.Navigation' );
goog.provide( 'zz.ide.models.NavigationDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );



/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
zz.ide.models.NavigationDatarow = function( dataset, opt_data ){

    /**
     * @type {string}
     */
    this.name = undefined;

    /**
     * @type {string}
     */
    this.icon = undefined;

    /**
     * @type {string}
     */
    this.color = undefined;

    /**
     * @type {string}
     */
    this.path = undefined;

    /**
     * @type {number}
     */
    this.type = undefined;

    /**
     * @type {boolean}
     */
    this.delimeter = undefined;

    /**
     * @type {boolean}
     */
    this.selected = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( zz.ide.models.NavigationDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
zz.ide.models.Navigation = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( zz.ide.models.Navigation, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {zz.ide.models.NavigationDatarow}
*/
zz.ide.models.Navigation.prototype.DatarowConstructor = zz.ide.models.NavigationDatarow;

/**
* Return zz.ide.models.NavigationDatarow schema object.
* @override
* @returns {Object}
*/
zz.ide.models.Navigation.prototype.getDatarowSchema = function( ){

return {
        name: {
                index: 0,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        icon: {
                index: 1,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        color: {
                index: 2,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        path: {
                index: 3,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        type: {
                index: 4,
                type: zz.models.enums.FieldType.NUMBER,
                required: false
        },
        delimeter: {
                index: 5,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        },
        selected: {
                index: 6,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        }
};
};