// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'zz.ide.models.Navigation' );
goog.provide( 'zz.ide.models.NavigationDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );



/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
zz.ide.models.NavigationDatarow = function( dataset, opt_data ){

    /**
     * @type {string}
     */
    this.title = undefined;

    /**
     * @type {string}
     */
    this.type = undefined;

    /**
     * @type {string}
     */
    this.path = undefined;

    /**
     * @type {string}
     */
    this.content = undefined;

    /**
     * @type {number}
     */
    this.count = undefined;

    /**
     * @type {zz.ide.models.Tree}
     */
    this.children = undefined;

    /**
     * @type {boolean}
     */
    this.isNavigationShow = undefined;

    /**
     * @type {string}
     */
    this.searchField = undefined;

    /**
     * @type {string}
     */
    this.searchPlaceholder = undefined;

    /**
     * @type {string}
     */
    this.searchButtonIcon = undefined;

    /**
     * @type {string}
     */
    this.searchBtnState = undefined;

    /**
     * @type {boolean}
     */
    this.isFolderOpen = undefined;

    /**
     * @type {boolean}
     */
    this.isContextShow = undefined;

    /**
     * @type {boolean}
     */
    this.isContextOpen = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( zz.ide.models.NavigationDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
zz.ide.models.Navigation = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( zz.ide.models.Navigation, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {zz.ide.models.NavigationDatarow}
*/
zz.ide.models.Navigation.prototype.DatarowConstructor = zz.ide.models.NavigationDatarow;

/**
* Return zz.ide.models.NavigationDatarow schema object.
* @override
* @returns {Object}
*/
zz.ide.models.Navigation.prototype.getDatarowSchema = function( ){

return {
        title: {
                index: 0,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        type: {
                index: 1,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        path: {
                index: 2,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        content: {
                index: 3,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        count: {
                index: 4,
                type: zz.models.enums.FieldType.NUMBER,
                required: false
        },
        children: {
                index: 5,
                type: zz.ide.models.Tree,
                required: false
        },
        isNavigationShow: {
                index: 6,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        },
        searchField: {
                index: 7,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        searchPlaceholder: {
                index: 8,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        searchButtonIcon: {
                index: 9,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        searchBtnState: {
                index: 10,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        isFolderOpen: {
                index: 11,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        },
        isContextShow: {
                index: 12,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        },
        isContextOpen: {
                index: 13,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        }
};
};