// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'zz.ide.models.Node' );
goog.provide( 'zz.ide.models.NodeDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );



/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
zz.ide.models.NodeDatarow = function( dataset, opt_data ){

    /**
     * @type {string}
     */
    this.title = undefined;

    /**
     * @type {string}
     */
    this.type = undefined;

    /**
     * @type {string}
     */
    this.path = undefined;

    /**
     * @type {string}
     */
    this.content = undefined;

    /**
     * @type {number}
     */
    this.count = undefined;

    /**
     * @type {boolean}
     */
    this.isopen = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( zz.ide.models.NodeDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
zz.ide.models.Node = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( zz.ide.models.Node, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {zz.ide.models.NodeDatarow}
*/
zz.ide.models.Node.prototype.DatarowConstructor = zz.ide.models.NodeDatarow;

/**
* Return zz.ide.models.NodeDatarow schema object.
* @override
* @returns {Object}
*/
zz.ide.models.Node.prototype.getDatarowSchema = function( ){

return {
        title: {
                index: 0,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        type: {
                index: 1,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        path: {
                index: 2,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        content: {
                index: 3,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        count: {
                index: 4,
                type: zz.models.enums.FieldType.NUMBER,
                required: false
        },
        isopen: {
                index: 5,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        }
};
};