// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'zz.ide.models.Search' );
goog.provide( 'zz.ide.models.SearchDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );



/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
zz.ide.models.SearchDatarow = function( dataset, opt_data ){

    /**
     * @type {string}
     */
    this.input = undefined;

    /**
     * @type {boolean}
     */
    this.focus = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( zz.ide.models.SearchDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
zz.ide.models.Search = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( zz.ide.models.Search, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {zz.ide.models.SearchDatarow}
*/
zz.ide.models.Search.prototype.DatarowConstructor = zz.ide.models.SearchDatarow;

/**
* Return zz.ide.models.SearchDatarow schema object.
* @override
* @returns {Object}
*/
zz.ide.models.Search.prototype.getDatarowSchema = function( ){

return {
        input: {
                index: 0,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        focus: {
                index: 1,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        }
};
};