// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'zz.ide.models.Services' );
goog.provide( 'zz.ide.models.ServicesDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );



/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
zz.ide.models.ServicesDatarow = function( dataset, opt_data ){

    /**
     * @type {string}
     */
    this.name = undefined;

    /**
     * @type {string}
     */
    this.icon = undefined;

    /**
     * @type {string}
     */
    this.action = undefined;

    /**
     * @type {string}
     */
    this.cssClass = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( zz.ide.models.ServicesDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
zz.ide.models.Services = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( zz.ide.models.Services, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {zz.ide.models.ServicesDatarow}
*/
zz.ide.models.Services.prototype.DatarowConstructor = zz.ide.models.ServicesDatarow;

/**
* Return zz.ide.models.ServicesDatarow schema object.
* @override
* @returns {Object}
*/
zz.ide.models.Services.prototype.getDatarowSchema = function( ){

return {
        name: {
                index: 0,
                type: zz.models.enums.FieldType.STRING,
                required: true
        },
        icon: {
                index: 1,
                type: zz.models.enums.FieldType.STRING,
                required: true
        },
        action: {
                index: 2,
                type: zz.models.enums.FieldType.STRING,
                required: true
        },
        cssClass: {
                index: 3,
                type: zz.models.enums.FieldType.STRING,
                required: false
        }
};
};