// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'zz.ide.models.Sidebar' );
goog.provide( 'zz.ide.models.SidebarDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );

goog.require( 'zz.ide.models.Navigation' );


/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
zz.ide.models.SidebarDatarow = function( dataset, opt_data ){

    /**
     * @type {zz.ide.models.Navigation}
     */
    this.navigation0 = undefined;

    /**
     * @type {zz.ide.models.Navigation}
     */
    this.navigation1 = undefined;

    /**
     * @type {zz.ide.models.Navigation}
     */
    this.navigation2 = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( zz.ide.models.SidebarDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
zz.ide.models.Sidebar = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( zz.ide.models.Sidebar, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {zz.ide.models.SidebarDatarow}
*/
zz.ide.models.Sidebar.prototype.DatarowConstructor = zz.ide.models.SidebarDatarow;

/**
* Return zz.ide.models.SidebarDatarow schema object.
* @override
* @returns {Object}
*/
zz.ide.models.Sidebar.prototype.getDatarowSchema = function( ){

return {
        navigation0: {
                index: 0,
                type: zz.ide.models.Navigation,
                required: false
        },
        navigation1: {
                index: 1,
                type: zz.ide.models.Navigation,
                required: false
        },
        navigation2: {
                index: 2,
                type: zz.ide.models.Navigation,
                required: false
        }
};
};