// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'zz.ide.models.Startpage' );
goog.provide( 'zz.ide.models.StartpageDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );



/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
zz.ide.models.StartpageDatarow = function( dataset, opt_data ){

    /**
     * @type {string}
     */
    this.title = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( zz.ide.models.StartpageDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
zz.ide.models.Startpage = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( zz.ide.models.Startpage, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {zz.ide.models.StartpageDatarow}
*/
zz.ide.models.Startpage.prototype.DatarowConstructor = zz.ide.models.StartpageDatarow;

/**
* Return zz.ide.models.StartpageDatarow schema object.
* @override
* @returns {Object}
*/
zz.ide.models.Startpage.prototype.getDatarowSchema = function( ){

return {
        title: {
                index: 0,
                type: zz.models.enums.FieldType.STRING,
                required: false
        }
};
};