// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'zz.ide.models.TernRequest' );
goog.provide( 'zz.ide.models.TernRequestDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );



/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
zz.ide.models.TernRequestDatarow = function( dataset, opt_data ){

    /**
     * @type {string}
     */
    this.query = undefined;

    /**
     * @type {string}
     */
    this.files = undefined;

    /**
     * @type {number}
     */
    this.timeout = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( zz.ide.models.TernRequestDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
zz.ide.models.TernRequest = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( zz.ide.models.TernRequest, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {zz.ide.models.TernRequestDatarow}
*/
zz.ide.models.TernRequest.prototype.DatarowConstructor = zz.ide.models.TernRequestDatarow;

/**
* Return zz.ide.models.TernRequestDatarow schema object.
* @override
* @returns {Object}
*/
zz.ide.models.TernRequest.prototype.getDatarowSchema = function( ){

return {
        query: {
                index: 0,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        files: {
                index: 1,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        timeout: {
                index: 2,
                type: zz.models.enums.FieldType.NUMBER,
                required: false
        }
};
};