// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'zz.ide.models.TreeNode' );
goog.provide( 'zz.ide.models.TreeNodeDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );



/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
zz.ide.models.TreeNodeDatarow = function( dataset, opt_data ){

    /**
     * @type {string}
     */
    this.title = undefined;

    /**
     * @type {zz.ide.models.TreeNode}
     */
    this.children = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( zz.ide.models.TreeNodeDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
zz.ide.models.TreeNode = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( zz.ide.models.TreeNode, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {zz.ide.models.TreeNodeDatarow}
*/
zz.ide.models.TreeNode.prototype.DatarowConstructor = zz.ide.models.TreeNodeDatarow;

/**
* Return zz.ide.models.TreeNodeDatarow schema object.
* @override
* @returns {Object}
*/
zz.ide.models.TreeNode.prototype.getDatarowSchema = function( ){

return {
        title: {
                index: 0,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        children: {
                index: 1,
                type: zz.ide.models.TreeNode,
                required: false
        }
};
};