// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'zz.ide.models.Tree' );
goog.provide( 'zz.ide.models.TreeDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );

goog.require( 'zz.ide.models.Context' );


/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
zz.ide.models.TreeDatarow = function( dataset, opt_data ){

    /**
     * @type {string}
     */
    this.title = undefined;

    /**
     * @type {string}
     */
    this.type = undefined;

    /**
     * @type {string}
     */
    this.path = undefined;

    /**
     * @type {string}
     */
    this.content = undefined;

    /**
     * @type {number}
     */
    this.count = undefined;

    /**
     * @type {zz.ide.models.Tree}
     */
    this.children = undefined;

    /**
     * @type {boolean}
     */
    this.isFolderOpen = undefined;

    /**
     * @type {boolean}
     */
    this.isContextShow = undefined;

    /**
     * @type {zz.ide.models.Context}
     */
    this.context = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( zz.ide.models.TreeDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
zz.ide.models.Tree = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( zz.ide.models.Tree, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {zz.ide.models.TreeDatarow}
*/
zz.ide.models.Tree.prototype.DatarowConstructor = zz.ide.models.TreeDatarow;

/**
* Return zz.ide.models.TreeDatarow schema object.
* @override
* @returns {Object}
*/
zz.ide.models.Tree.prototype.getDatarowSchema = function( ){

return {
        title: {
                index: 0,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        type: {
                index: 1,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        path: {
                index: 2,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        content: {
                index: 3,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        count: {
                index: 4,
                type: zz.models.enums.FieldType.NUMBER,
                required: false
        },
        children: {
                index: 5,
                type: zz.ide.models.Tree,
                required: false
        },
        isFolderOpen: {
                index: 6,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        },
        isContextShow: {
                index: 7,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        },
        context: {
                index: 8,
                type: zz.ide.models.Context,
                required: false
        }
};
};