// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'zz.ide.models.View' );
goog.provide( 'zz.ide.models.ViewDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );

goog.require( 'zz.ide.models.Ace' );
goog.require( 'zz.ide.models.Filelist' );
goog.require( 'zz.ide.models.Blankfolder' );


/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
zz.ide.models.ViewDatarow = function( dataset, opt_data ){

    /**
     * @type {zz.ide.models.Ace}
     */
    this.ace = undefined;

    /**
     * @type {zz.ide.models.Filelist}
     */
    this.filelist = undefined;

    /**
     * @type {zz.ide.models.Startpage}
     */
    this.blankfolder = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( zz.ide.models.ViewDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
zz.ide.models.View = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( zz.ide.models.View, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {zz.ide.models.ViewDatarow}
*/
zz.ide.models.View.prototype.DatarowConstructor = zz.ide.models.ViewDatarow;

/**
* Return zz.ide.models.ViewDatarow schema object.
* @override
* @returns {Object}
*/
zz.ide.models.View.prototype.getDatarowSchema = function( ){

return {
        ace: {
                index: 0,
                type: zz.ide.models.Ace,
                required: false
        },
        filelist: {
                index: 1,
                type: zz.ide.models.Filelist,
                required: false
        },
        blankfolder: {
                index: 2,
                type: zz.ide.models.Startpage,
                required: false
        }
};
};