// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'zz.ide.models.WebServerRunner' );
goog.provide( 'zz.ide.models.WebServerRunnerDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );



/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
zz.ide.models.WebServerRunnerDatarow = function( dataset, opt_data ){

    /**
     * @type {string}
     */
    this.stderr = undefined;

    /**
     * @type {boolean}
     */
    this.isrunning = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( zz.ide.models.WebServerRunnerDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
zz.ide.models.WebServerRunner = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( zz.ide.models.WebServerRunner, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {zz.ide.models.WebServerRunnerDatarow}
*/
zz.ide.models.WebServerRunner.prototype.DatarowConstructor = zz.ide.models.WebServerRunnerDatarow;

/**
* Return zz.ide.models.WebServerRunnerDatarow schema object.
* @override
* @returns {Object}
*/
zz.ide.models.WebServerRunner.prototype.getDatarowSchema = function( ){

return {
        stderr: {
                index: 0,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        isrunning: {
                index: 1,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        }
};
};